call_parentheses = "NoSingleTable"
collapse_simple_statement = "Never"
column_width = 120
line_endings = "Windows"
indent_width = 4
indent_type = "Tabs"
space_after_function_names = "Never"
syntax = "Luau"
quote_style = "AutoPreferDouble"

[sort_requires]
enabled = true