name = "pesde/selene"
version = "0.29.0"
description = "A blazing-fast modern Lua linter written in Rust"
authors = ["CompeyDev <hi@devcomp.xyz>", "Kampfkarren <kampfkarren@gmail.com>"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/selene"
private = false
includes = ["init.luau", "README.md", "pesde.toml"]

[target]
environment = "lune"
bin = "init.luau"

[engines]
pesde = "^0.6.0"
lune = "^0.8.7"

[dependencies.core]
name = "pesde/toolchainlib"
version = "^0.1.15"
index = "https://github.com/pesde-pkg/index"
target = "lune"

[dependencies.option]
name = "lukadev_0/option"
version = "^1.2.0"
index = "https://github.com/pesde-pkg/index"

[dependencies.result]
name = "lukadev_0/result"
version = "^1.2.0"
index = "https://github.com/pesde-pkg/index"
